### ISSUE TITLE
SCHAC LDIF file can not be imported.

### ISSUE THREAD

**Issue by malavolti** [REFEDS/SCHAC#4]
Dear @hlflanagan ,
I've tried to import the [openldap.ldif](https://github.com/REFEDS/SCHAC/blob/main/schema/openldap.ldif) file without success.

What I missing?

Here you can find the working version 1.5.0 that I'm using now (if you want to add it to the git repo):

https://github.com/malavolti/ansible-shibboleth/blob/master/roles/openldap/files/schac-20150413.ldif

Best Regards,
Marco

```
# ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/schac.ldif
SASL/EXTERNAL authentication started
SASL username: gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth
SASL SSF: 0
adding new entry "cn=schac,cn=schema,cn=config"
ldap_add: Other (e.g., implementation specific) error (80)
	additional info: olcAttributeTypes: Unexpected token before DESC 'RFC 3066 code for preferred language of communication'EQUALITY caseExactMatchSINGLE-VALUESYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
```

**Comment by hlflanagan** [comment]
Thank you for the report! This has been fixed.
